autodetect: false
uses:
  - django

ignore-paths:
  - dist
  - docs
  - build-tool
  - rootfs
  - etc

pylint:
  disable:
    - keyword-arg-before-vararg
    - too-many-arguments

pep8:
  disable:
    - E131
